classes:
- id: 0
  name: TV
  display_name: TV
  prompt: television
  enabled: true
- id: 1
  name: person
  display_name: Person
  prompt: person
  enabled: true
- id: 2
  name: chair
  display_name: Chair
  prompt: chair
  enabled: true
- id: 3
  name: bottle
  display_name: Bottle
  prompt: bottle
  enabled: false
- id: 4
  name: laptop
  display_name: Laptop
  prompt: laptop
  enabled: false
- id: 5
  name: Bear
  enabled: true
- id: 6
  name: Box
  enabled: true
- id: 7
  name: Cat
  enabled: true
- id: 8
  name: KeyBoard
  enabled: true
- id: 9
  name: Window
  enabled: true
- id: 10
  name: flower
  enabled: true
- id: 11
  name: Sign
  enabled: true
- id: 12
  name: Car
  enabled: true
